Repository sdsc-ordes/modos-api, pull requests merged in 2024-06, with the labels that each got.

#55 docs(readme): add credits
  README.md
Labels: documentation

#62 fix(server): reload minio filesystem for each server query
  deploy/modos-server/server.py
Labels: bug

#64 fix: auto upload cram index
  modos/api.py
  modos/cram.py
  modos/helpers.py
  tests/conftest.py
  tests/test_api_local.py
  tests/test_api_remote.py
  tests/test_cli_local.py
Labels: bug

#68 Refactor/remote
  docs/tutorials/modo_arrays.md
  modos/api.py
  modos/cli.py
  modos/cram.py
  modos/helpers.py
  modos/storage.py
  tests/test_cli_local.py
Labels: enhancement

#69 chore: add issue templates for feature requests and bug reports.
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: enhancement

#70 fix: consistent ids
  data/ex/data.zarr/.zattrs
  data/ex/data.zarr/.zmetadata
  data/ex/data.zarr/assay/assay1/.zattrs
  data/ex/data.zarr/data/calls1/.zattrs
  data/ex/data.zarr/data/demo1/.zattrs
  modos/api.py
  modos/helpers.py
  tests/test_api_local.py
  tests/test_api_remote.py
  tests/test_cli_local.py
Labels: bug
