Repository sdsc-ordes/modos-api, pull requests merged in 2024-08, with the labels that each got.

#90 feat: streamline remote options
  deploy/docker-compose.yml
  deploy/modos-server/server.py
  modos/__init__.py
  modos/api.py
  modos/cli.py
  modos/genomics/htsget.py
  modos/remote.py
  modos/storage.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_api_remote.py
Labels: enhancement

#95 ci: build and publish at pypi/test-pypi
  .github/workflows/poetry-publish.yml
  .github/workflows/poetry-pytest.yml
  .github/workflows/poetry-test-publish.yml
  docs/conf.py
  pyproject.toml
Labels: enhancement

#97 docs(tutorial): update remote and genomics
  docs/tutorials/genomics_streaming.md
  docs/tutorials/modo_access.md
  docs/tutorials/modo_remote.md
  docs/tutorials/tutorials.md
Labels: documentation

#99 fix(rdf): inject schema:identifier
  modos/helpers/schema.py
Labels: bug

#98 feat(cli, api):show only target element
  modos/api.py
  modos/cli.py
Labels: enhancement
