Repository sdsc-ordes/modos-api, pull requests merged in 2024-07, with the labels that each got.

#73 feat: auto update last_update_date attr
  modos/api.py
Labels: enhancement

#71 fix: client-side region-filter on htsget streams
  modos/api.py
  modos/cram.py
  modos/helpers.py
Labels: bug

#77 refactor: region type
  modos/api.py
  modos/cli.py
  modos/cram.py
  modos/file_utils.py
  modos/helpers/__init__.py
  modos/helpers/genomics.py
  modos/helpers/region.py
  modos/helpers/schema.py
  modos/introspection.py
  modos/io.py
  modos/rdf.py
  modos/storage.py
  tests/test_region.py
Labels: enhancement

#76 feat(cli, api): remove modo
  modos/api.py
  modos/cli.py
  modos/storage.py
  tests/test_api_local.py
  tests/test_api_remote.py
  tests/test_cli_local.py
Labels: enhancement

#78 feat: htsget client
  docs/tutorials/modo_provider.md
  docs/tutorials/modo_remote.md
  modos/api.py
  modos/cli.py
  modos/cram.py
  modos/file_utils.py
  modos/genomics/__init__.py
  modos/genomics/cram.py
  modos/genomics/formats.py
  modos/genomics/htsget.py
  modos/genomics/region.py
  modos/helpers/genomics.py
  modos/io.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_api_local.py
  tests/test_api_remote.py
  tests/test_region.py
Labels: enhancement

#80 docs(readme): styling + update examples
  CONTRIBUTING.md
  README.md
  docs/development_guide.md
Labels: documentation

#83 fix(api): update new values in update_element
  modos/api.py
  modos/helpers/schema.py
  tests/test_api_local.py
Labels: bug

#89 feat(cli): update modo from yaml file
  modos/api.py
  modos/cli.py
Labels: enhancement
