Repository sdsc-ordes/modos-api, pull requests merged in 2025-05, with the labels that each got.

#125 refactor: adhere to template
  .envrc
  .github/workflows/docker-publish.yml
  .github/workflows/sphinx-docs.yml
  .github/workflows/uv-publish.yml
  .github/workflows/uv-pytest.yml
  .github/workflows/uv-test-publish.yml
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  deploy/modos-server/Dockerfile
  docs/conf.py
  docs/development_guide.md
  modos/__init__.py
  poetry.lock
  pyproject.toml
  src/modos/__init__.py
  src/modos/api.py
  src/modos/cli.py
  src/modos/codes.py
  src/modos/genomics/__init__.py
  src/modos/genomics/cram.py
  src/modos/genomics/formats.py
  src/modos/genomics/htsget.py
  src/modos/genomics/refget.py
  src/modos/genomics/region.py
  src/modos/helpers/__init__.py
  src/modos/helpers/schema.py
  src/modos/io.py
  src/modos/metabolomics/__init__.py
  src/modos/metabolomics/mztab.py
  src/modos/prompt.py
  src/modos/rdf.py
  src/modos/remote.py
  src/modos/storage.py
  tests/conftest.py
  tests/test_api_local.py
  tests/test_api_remote.py
  tests/test_cli_local.py
  tools/deploy/.example.env
  tools/deploy/README.md
  tools/deploy/docker-compose.yml
  tools/deploy/fuzon/Dockerfile
  tools/deploy/fuzon/config.json.template
  tools/deploy/fuzon/docker-entrypoint.sh
  tools/deploy/htsget/Dockerfile
  tools/deploy/htsget/config.toml.template
  tools/deploy/htsget/docker-entrypoint.sh
  tools/deploy/modos-server/Dockerfile
  tools/deploy/modos-server/server.py
  tools/deploy/nginx/default.conf.template
  tools/deploy/refget/Dockerfile
  tools/deploy/refget/config.properties.template
  tools/deploy/refget/docker-entrypoint.sh
  tools/image/Dockerfile
  tools/nix/flake.lock
  tools/nix/flake.nix
  uv.lock
Labels: enhancement

#126 fix(server): api compatibility for /meta and /get
  tools/deploy/modos-server/server.py
Labels: bug

#130 feat: logger
  .pre-commit-config.yaml
  pyproject.toml
  src/modos/api.py
  src/modos/cli.py
  src/modos/genomics/refget.py
  src/modos/logging.py
  src/modos/storage.py
  tools/deploy/modos-server/server.py
  uv.lock
Labels: enhancement

#127 feat: local crypt4gh encryption
  data/ex/data.zarr/.zmetadata
  pyproject.toml
  src/modos/api.py
  src/modos/cli.py
  src/modos/genomics/c4gh.py
  src/modos/genomics/formats.py
  src/modos/helpers/schema.py
  src/modos/storage.py
  tests/conftest.py
  tests/test_api_remote.py
  tests/test_cli_local.py
  uv.lock
Labels: enhancement

#133 refactor(api): explicit file handling
  src/modos/api.py
  src/modos/cli.py
  src/modos/helpers/schema.py
Labels: enhancement

#136 docs: add encryption and upload sections
  docs/tutorials/genomics_streaming.md
  docs/tutorials/modo_remote.md
Labels: documentation

#138 fix(api): sequential encryption
  src/modos/genomics/formats.py
  src/modos/helpers/schema.py
Labels: bug
